ifdef CONFIG_DYNAMIC_PLUGINS
$(PLUGIN_DIR)/$(PLUGIN_NAME).$(PLUGIN_EXT): $(PLUGIN_SRCS)
	$(CC) $(CFLAGS) $(LDFLAGS) -fPIC -shared $^ -o $@

all: $(PLUGIN_DIR)/$(PLUGIN_NAME).$(PLUGIN_EXT)

CLEAN += $(PLUGIN_DIR)/$(PLUGIN_NAME).$(PLUGIN_EXT)

else
    SRCS += $(PLUGIN_SRCS)
endif
