ifdef CONFIG_DYNAMIC_PLUGINS

PLUGIN_OBJS := $(subst .c,.o,$(PLUGIN_SRCS))
PLUGIN_FILE := $(PLUGIN_NAME)$(PLUGIN_EXT)
PLUGIN_TARGET := $(PLUGIN_FILE)

$(PLUGIN_OBJS): %.o: %.c
	$(CC) $(CFLAGS) $(MODULE_CFLAGS) -c -o $@ $<

$(PLUGIN_TARGET): $(PLUGIN_OBJS)
	    $(CC) $(LDFLAGS) $(MODULE_LDFLAGS) -o $@ $^

.PHONY: clean_$(PLUGIN_NAME) install_$(PLUGIN_NAME)

clean_$(PLUGIN_NAME): PLUGIN_OBJS := $(PLUGIN_OBJS)
clean_$(PLUGIN_NAME): PLUGIN_TARGET := $(PLUGIN_TARGET)
clean_$(PLUGIN_NAME):
	rm -f $(PLUGIN_OBJS) $(PLUGIN_TARGET)

install_$(PLUGIN_NAME): PLUGIN_TARGET := $(PLUGIN_TARGET)
install_$(PLUGIN_NAME): PLUGIN_FILE := $(PLUGIN_FILE)
install_$(PLUGIN_NAME): $(PREFIX_PLUGINS) $(PLUGIN_TARGET)
	install -m 755 $(PLUGIN_TARGET) $(PREFIX_PLUGINS)/$(PLUGIN_FILE)

all: $(PLUGIN_TARGET)
clean: clean_$(PLUGIN_NAME)
install: install_$(PLUGIN_NAME)

else
    SRCS += $(PLUGIN_SRCS)
endif
