/*
 * Generated by gdbus-codegen 2.48.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __SHAIRPORT_SYNC_MPRIS_PLAYER_INTERFACE_H__
#define __SHAIRPORT_SYNC_MPRIS_PLAYER_INTERFACE_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.mpris.MediaPlayer2.Player */

#define TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER (org_mpris_media_player2_player_get_type ())
#define ORG_MPRIS_MEDIA_PLAYER2_PLAYER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER, OrgMprisMediaPlayer2Player))
#define IS_ORG_MPRIS_MEDIA_PLAYER2_PLAYER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER))
#define ORG_MPRIS_MEDIA_PLAYER2_PLAYER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER, OrgMprisMediaPlayer2PlayerIface))

struct _OrgMprisMediaPlayer2Player;
typedef struct _OrgMprisMediaPlayer2Player OrgMprisMediaPlayer2Player;
typedef struct _OrgMprisMediaPlayer2PlayerIface OrgMprisMediaPlayer2PlayerIface;

struct _OrgMprisMediaPlayer2PlayerIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_next) (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_open_uri) (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_Uri);

  gboolean (*handle_pause) (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_play) (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_play_pause) (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_previous) (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_seek) (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation,
    gint64 arg_Offset);

  gboolean (*handle_set_position) (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_TrackId,
    gint64 arg_Position);

  gboolean (*handle_stop) (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_stop_after_current) (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

  gboolean  (*get_can_control) (OrgMprisMediaPlayer2Player *object);

  gboolean  (*get_can_go_next) (OrgMprisMediaPlayer2Player *object);

  gboolean  (*get_can_go_previous) (OrgMprisMediaPlayer2Player *object);

  gboolean  (*get_can_pause) (OrgMprisMediaPlayer2Player *object);

  gboolean  (*get_can_play) (OrgMprisMediaPlayer2Player *object);

  gboolean  (*get_can_seek) (OrgMprisMediaPlayer2Player *object);

  const gchar * (*get_loop_status) (OrgMprisMediaPlayer2Player *object);

  gdouble  (*get_maximum_rate) (OrgMprisMediaPlayer2Player *object);

  GVariant * (*get_metadata) (OrgMprisMediaPlayer2Player *object);

  gdouble  (*get_minimum_rate) (OrgMprisMediaPlayer2Player *object);

  const gchar * (*get_playback_status) (OrgMprisMediaPlayer2Player *object);

  gint64  (*get_position) (OrgMprisMediaPlayer2Player *object);

  gdouble  (*get_rate) (OrgMprisMediaPlayer2Player *object);

  gboolean  (*get_shuffle) (OrgMprisMediaPlayer2Player *object);

  gdouble  (*get_volume) (OrgMprisMediaPlayer2Player *object);

  void (*seeked) (
    OrgMprisMediaPlayer2Player *object,
    gint64 arg_Position);

};

GType org_mpris_media_player2_player_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_mpris_media_player2_player_interface_info (void);
guint org_mpris_media_player2_player_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_mpris_media_player2_player_complete_next (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void org_mpris_media_player2_player_complete_previous (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void org_mpris_media_player2_player_complete_pause (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void org_mpris_media_player2_player_complete_play_pause (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void org_mpris_media_player2_player_complete_stop (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void org_mpris_media_player2_player_complete_stop_after_current (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void org_mpris_media_player2_player_complete_play (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void org_mpris_media_player2_player_complete_seek (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void org_mpris_media_player2_player_complete_set_position (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);

void org_mpris_media_player2_player_complete_open_uri (
    OrgMprisMediaPlayer2Player *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void org_mpris_media_player2_player_emit_seeked (
    OrgMprisMediaPlayer2Player *object,
    gint64 arg_Position);



/* D-Bus method calls: */
void org_mpris_media_player2_player_call_next (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_mpris_media_player2_player_call_next_finish (
    OrgMprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_mpris_media_player2_player_call_next_sync (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void org_mpris_media_player2_player_call_previous (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_mpris_media_player2_player_call_previous_finish (
    OrgMprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_mpris_media_player2_player_call_previous_sync (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void org_mpris_media_player2_player_call_pause (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_mpris_media_player2_player_call_pause_finish (
    OrgMprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_mpris_media_player2_player_call_pause_sync (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void org_mpris_media_player2_player_call_play_pause (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_mpris_media_player2_player_call_play_pause_finish (
    OrgMprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_mpris_media_player2_player_call_play_pause_sync (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void org_mpris_media_player2_player_call_stop (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_mpris_media_player2_player_call_stop_finish (
    OrgMprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_mpris_media_player2_player_call_stop_sync (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void org_mpris_media_player2_player_call_stop_after_current (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_mpris_media_player2_player_call_stop_after_current_finish (
    OrgMprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_mpris_media_player2_player_call_stop_after_current_sync (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void org_mpris_media_player2_player_call_play (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_mpris_media_player2_player_call_play_finish (
    OrgMprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_mpris_media_player2_player_call_play_sync (
    OrgMprisMediaPlayer2Player *proxy,
    GCancellable *cancellable,
    GError **error);

void org_mpris_media_player2_player_call_seek (
    OrgMprisMediaPlayer2Player *proxy,
    gint64 arg_Offset,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_mpris_media_player2_player_call_seek_finish (
    OrgMprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_mpris_media_player2_player_call_seek_sync (
    OrgMprisMediaPlayer2Player *proxy,
    gint64 arg_Offset,
    GCancellable *cancellable,
    GError **error);

void org_mpris_media_player2_player_call_set_position (
    OrgMprisMediaPlayer2Player *proxy,
    const gchar *arg_TrackId,
    gint64 arg_Position,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_mpris_media_player2_player_call_set_position_finish (
    OrgMprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_mpris_media_player2_player_call_set_position_sync (
    OrgMprisMediaPlayer2Player *proxy,
    const gchar *arg_TrackId,
    gint64 arg_Position,
    GCancellable *cancellable,
    GError **error);

void org_mpris_media_player2_player_call_open_uri (
    OrgMprisMediaPlayer2Player *proxy,
    const gchar *arg_Uri,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_mpris_media_player2_player_call_open_uri_finish (
    OrgMprisMediaPlayer2Player *proxy,
    GAsyncResult *res,
    GError **error);

gboolean org_mpris_media_player2_player_call_open_uri_sync (
    OrgMprisMediaPlayer2Player *proxy,
    const gchar *arg_Uri,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *org_mpris_media_player2_player_get_playback_status (OrgMprisMediaPlayer2Player *object);
gchar *org_mpris_media_player2_player_dup_playback_status (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_playback_status (OrgMprisMediaPlayer2Player *object, const gchar *value);

const gchar *org_mpris_media_player2_player_get_loop_status (OrgMprisMediaPlayer2Player *object);
gchar *org_mpris_media_player2_player_dup_loop_status (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_loop_status (OrgMprisMediaPlayer2Player *object, const gchar *value);

gdouble org_mpris_media_player2_player_get_rate (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_rate (OrgMprisMediaPlayer2Player *object, gdouble value);

gboolean org_mpris_media_player2_player_get_shuffle (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_shuffle (OrgMprisMediaPlayer2Player *object, gboolean value);

GVariant *org_mpris_media_player2_player_get_metadata (OrgMprisMediaPlayer2Player *object);
GVariant *org_mpris_media_player2_player_dup_metadata (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_metadata (OrgMprisMediaPlayer2Player *object, GVariant *value);

gdouble org_mpris_media_player2_player_get_volume (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_volume (OrgMprisMediaPlayer2Player *object, gdouble value);

gint64 org_mpris_media_player2_player_get_position (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_position (OrgMprisMediaPlayer2Player *object, gint64 value);

gdouble org_mpris_media_player2_player_get_minimum_rate (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_minimum_rate (OrgMprisMediaPlayer2Player *object, gdouble value);

gdouble org_mpris_media_player2_player_get_maximum_rate (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_maximum_rate (OrgMprisMediaPlayer2Player *object, gdouble value);

gboolean org_mpris_media_player2_player_get_can_go_next (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_can_go_next (OrgMprisMediaPlayer2Player *object, gboolean value);

gboolean org_mpris_media_player2_player_get_can_go_previous (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_can_go_previous (OrgMprisMediaPlayer2Player *object, gboolean value);

gboolean org_mpris_media_player2_player_get_can_play (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_can_play (OrgMprisMediaPlayer2Player *object, gboolean value);

gboolean org_mpris_media_player2_player_get_can_pause (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_can_pause (OrgMprisMediaPlayer2Player *object, gboolean value);

gboolean org_mpris_media_player2_player_get_can_seek (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_can_seek (OrgMprisMediaPlayer2Player *object, gboolean value);

gboolean org_mpris_media_player2_player_get_can_control (OrgMprisMediaPlayer2Player *object);
void org_mpris_media_player2_player_set_can_control (OrgMprisMediaPlayer2Player *object, gboolean value);


/* ---- */

#define TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_PROXY (org_mpris_media_player2_player_proxy_get_type ())
#define ORG_MPRIS_MEDIA_PLAYER2_PLAYER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_PROXY, OrgMprisMediaPlayer2PlayerProxy))
#define ORG_MPRIS_MEDIA_PLAYER2_PLAYER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_PROXY, OrgMprisMediaPlayer2PlayerProxyClass))
#define ORG_MPRIS_MEDIA_PLAYER2_PLAYER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_PROXY, OrgMprisMediaPlayer2PlayerProxyClass))
#define IS_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_PROXY))
#define IS_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_PROXY))

typedef struct _OrgMprisMediaPlayer2PlayerProxy OrgMprisMediaPlayer2PlayerProxy;
typedef struct _OrgMprisMediaPlayer2PlayerProxyClass OrgMprisMediaPlayer2PlayerProxyClass;
typedef struct _OrgMprisMediaPlayer2PlayerProxyPrivate OrgMprisMediaPlayer2PlayerProxyPrivate;

struct _OrgMprisMediaPlayer2PlayerProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgMprisMediaPlayer2PlayerProxyPrivate *priv;
};

struct _OrgMprisMediaPlayer2PlayerProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_mpris_media_player2_player_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgMprisMediaPlayer2PlayerProxy, g_object_unref)
#endif

void org_mpris_media_player2_player_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgMprisMediaPlayer2Player *org_mpris_media_player2_player_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgMprisMediaPlayer2Player *org_mpris_media_player2_player_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_mpris_media_player2_player_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgMprisMediaPlayer2Player *org_mpris_media_player2_player_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgMprisMediaPlayer2Player *org_mpris_media_player2_player_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON (org_mpris_media_player2_player_skeleton_get_type ())
#define ORG_MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON, OrgMprisMediaPlayer2PlayerSkeleton))
#define ORG_MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON, OrgMprisMediaPlayer2PlayerSkeletonClass))
#define ORG_MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON, OrgMprisMediaPlayer2PlayerSkeletonClass))
#define IS_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON))
#define IS_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_MPRIS_MEDIA_PLAYER2_PLAYER_SKELETON))

typedef struct _OrgMprisMediaPlayer2PlayerSkeleton OrgMprisMediaPlayer2PlayerSkeleton;
typedef struct _OrgMprisMediaPlayer2PlayerSkeletonClass OrgMprisMediaPlayer2PlayerSkeletonClass;
typedef struct _OrgMprisMediaPlayer2PlayerSkeletonPrivate OrgMprisMediaPlayer2PlayerSkeletonPrivate;

struct _OrgMprisMediaPlayer2PlayerSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgMprisMediaPlayer2PlayerSkeletonPrivate *priv;
};

struct _OrgMprisMediaPlayer2PlayerSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_mpris_media_player2_player_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgMprisMediaPlayer2PlayerSkeleton, g_object_unref)
#endif

OrgMprisMediaPlayer2Player *org_mpris_media_player2_player_skeleton_new (void);


G_END_DECLS

#endif /* __SHAIRPORT_SYNC_MPRIS_PLAYER_INTERFACE_H__ */
